In [1]:
import pandas as pd

books = pd.read_csv("books_with_categories.csv")

In [4]:
from transformers import pipeline

classifier = pipeline("text-classification" , model = "SamLowe/roberta-base-go_emotions" ,top_k = None )

classifier(" I love you")

Device set to use cpu

[[{'label': 'love', 'score': 0.9499284029006958},
  {'label': 'admiration', 'score': 0.030244318768382072},
  {'label': 'approval', 'score': 0.018024533987045288},
  {'label': 'neutral', 'score': 0.01158155407756567},
  {'label': 'joy', 'score': 0.008180981501936913},
  {'label': 'optimism', 'score': 0.007421193178743124},
  {'label': 'gratitude', 'score': 0.0071630533784627914},
  {'label': 'desire', 'score': 0.00576998433098197},
  {'label': 'annoyance', 'score': 0.00525943748652935},
  {'label': 'caring', 'score': 0.005007175728678703},
  {'label': 'anger', 'score': 0.0045594582334160805},
  {'label': 'disapproval', 'score': 0.0045311967842280865},
  {'label': 'realization', 'score': 0.004251265432685614},
  {'label': 'sadness', 'score': 0.004171949345618486},
  {'label': 'disappointment', 'score': 0.0037027080543339252},
  {'label': 'excitement', 'score': 0.0036139762960374355},
  {'label': 'amusement', 'score': 0.0031080180779099464},
  {'label': 'confusion', 'score': 0.0025786785408854485},
  {'label': 'disgust', 'score': 0.0022876563016325235},
  {'label': 'curiosity', 'score': 0.0019616454374045134},
  {'label': 'surprise', 'score': 0.0016398160951212049},
  {'label': 'remorse', 'score': 0.0014994749799370766},
  {'label': 'fear', 'score': 0.0009538474841974676},
  {'label': 'nervousness', 'score': 0.0005840370431542397},
  {'label': 'embarrassment', 'score': 0.0005504368455149233},
  {'label': 'grief', 'score': 0.00042190938256680965},
  {'label': 'pride', 'score': 0.00038677678094245493},
  {'label': 'relief', 'score': 0.00035014754394069314}]]

In [5]:
classifier(books["description"][0])

[[{'label': 'neutral', 'score': 0.4820651113986969},
  {'label': 'sadness', 'score': 0.09990358352661133},
  {'label': 'admiration', 'score': 0.09494038671255112},
  {'label': 'approval', 'score': 0.06846713274717331},
  {'label': 'joy', 'score': 0.03670448437333107},
  {'label': 'realization', 'score': 0.025667576119303703},
  {'label': 'disappointment', 'score': 0.022905196994543076},
  {'label': 'caring', 'score': 0.010355029255151749},
  {'label': 'relief', 'score': 0.00962989591062069},
  {'label': 'annoyance', 'score': 0.00626142555847764},
  {'label': 'optimism', 'score': 0.006212251260876656},
  {'label': 'excitement', 'score': 0.006100698374211788},
  {'label': 'grief', 'score': 0.005787441041320562},
  {'label': 'pride', 'score': 0.005556589923799038},
  {'label': 'desire', 'score': 0.00468267360702157},
  {'label': 'nervousness', 'score': 0.003790182527154684},
  {'label': 'disapproval', 'score': 0.003336826106533408},
  {'label': 'love', 'score': 0.003214039374142885},
  {'label': 'fear', 'score': 0.0030567890498787165},
  {'label': 'amusement', 'score': 0.0022629175800830126},
  {'label': 'disgust', 'score': 0.0014760736376047134},
  {'label': 'surprise', 'score': 0.0012264817487448454},
  {'label': 'anger', 'score': 0.0009885987965390086},
  {'label': 'embarrassment', 'score': 0.0009525750647298992},
  {'label': 'remorse', 'score': 0.0009374356595799327},
  {'label': 'curiosity', 'score': 0.0007846528314985335},
  {'label': 'gratitude', 'score': 0.0007571439491584897},
  {'label': 'confusion', 'score': 0.0006176640745252371}]]

In [6]:
classifier(books["description"][0].split("."))

[[{'label': 'excitement', 'score': 0.4950507879257202},
  {'label': 'admiration', 'score': 0.29842227697372437},
  {'label': 'neutral', 'score': 0.11334887892007828},
  {'label': 'approval', 'score': 0.06156652793288231},
  {'label': 'surprise', 'score': 0.025452643632888794},
  {'label': 'curiosity', 'score': 0.020611189305782318},
  {'label': 'joy', 'score': 0.013649096712470055},
  {'label': 'love', 'score': 0.012229564599692822},
  {'label': 'desire', 'score': 0.012063340283930302},
  {'label': 'optimism', 'score': 0.005851097404956818},
  {'label': 'realization', 'score': 0.004697063472121954},
  {'label': 'annoyance', 'score': 0.002989330794662237},
  {'label': 'pride', 'score': 0.0025997976772487164},
  {'label': 'confusion', 'score': 0.0024072828236967325},
  {'label': 'amusement', 'score': 0.0021955484990030527},
  {'label': 'disapproval', 'score': 0.0021141960751265287},
  {'label': 'disappointment', 'score': 0.0019814688712358475},
  {'label': 'disgust', 'score': 0.0014362820656970143},
  {'label': 'fear', 'score': 0.001415332080796361},
  {'label': 'anger', 'score': 0.001288198516704142},
  {'label': 'caring', 'score': 0.001193404896184802},
  {'label': 'sadness', 'score': 0.001169283059425652},
  {'label': 'gratitude', 'score': 0.0008985294844023883},
  {'label': 'relief', 'score': 0.0008879499509930611},
  {'label': 'nervousness', 'score': 0.0006956649012863636},
  {'label': 'embarrassment', 'score': 0.00044948080903850496},
  {'label': 'grief', 'score': 0.0004383960331324488},
  {'label': 'remorse', 'score': 0.0002430182066746056}],
 [{'label': 'neutral', 'score': 0.9304519891738892},
  {'label': 'approval', 'score': 0.03257760778069496},
  {'label': 'realization', 'score': 0.01269619632512331},
  {'label': 'admiration', 'score': 0.009453455917537212},
  {'label': 'annoyance', 'score': 0.006214241497218609},
  {'label': 'disapproval', 'score': 0.0029011350125074387},
  {'label': 'disappointment', 'score': 0.002652894239872694},
  {'label': 'optimism', 'score': 0.0019252232741564512},
  {'label': 'amusement', 'score': 0.001745107350870967},
  {'label': 'disgust', 'score': 0.0016568965511396527},
  {'label': 'confusion', 'score': 0.0016196834621950984},
  {'label': 'sadness', 'score': 0.0014964565634727478},
  {'label': 'anger', 'score': 0.001491309143602848},
  {'label': 'joy', 'score': 0.0013627652078866959},
  {'label': 'excitement', 'score': 0.001086628995835781},
  {'label': 'gratitude', 'score': 0.0009999192552641034},
  {'label': 'love', 'score': 0.0009145587682723999},
  {'label': 'fear', 'score': 0.0008080743718892336},
  {'label': 'curiosity', 'score': 0.000741882948204875},
  {'label': 'surprise', 'score': 0.0006469797226600349},
  {'label': 'caring', 'score': 0.0006131510017439723},
  {'label': 'desire', 'score': 0.0004939808277413249},
  {'label': 'pride', 'score': 0.0004914437886327505},
  {'label': 'embarrassment', 'score': 0.0004754800465889275},
  {'label': 'relief', 'score': 0.00038349133683368564},
  {'label': 'remorse', 'score': 0.00026745168725028634},
  {'label': 'grief', 'score': 0.00026091004838235676},
  {'label': 'nervousness', 'score': 0.00018528825603425503}],
 [{'label': 'neutral', 'score': 0.9456536769866943},
  {'label': 'realization', 'score': 0.030264271423220634},
  {'label': 'approval', 'score': 0.022307084873318672},
  {'label': 'sadness', 'score': 0.00860905833542347},
  {'label': 'disappointment', 'score': 0.00857413187623024},
  {'label': 'disapproval', 'score': 0.006441458128392696},
  {'label': 'annoyance', 'score': 0.005673831794410944},
  {'label': 'optimism', 'score': 0.003350455081090331},
  {'label': 'admiration', 'score': 0.002964984392747283},
  {'label': 'confusion', 'score': 0.0022469523828476667},
  {'label': 'joy', 'score': 0.0019315161043778062},
  {'label': 'fear', 'score': 0.0017752181738615036},
  {'label': 'amusement', 'score': 0.00169931270647794},
  {'label': 'disgust', 'score': 0.0016391252866014838},
  {'label': 'caring', 'score': 0.0015369165921583772},
  {'label': 'gratitude', 'score': 0.0014884908450767398},
  {'label': 'desire', 'score': 0.0014817964984104037},
  {'label': 'excitement', 'score': 0.001060292823240161},
  {'label': 'anger', 'score': 0.0010424390202388167},
  {'label': 'relief', 'score': 0.0010348428040742874},
  {'label': 'love', 'score': 0.0010253525106236339},
  {'label': 'surprise', 'score': 0.0009858720004558563},
  {'label': 'embarrassment', 'score': 0.0009728085133247077},
  {'label': 'grief', 'score': 0.0009689646540209651},
  {'label': 'remorse', 'score': 0.0009397840476594865},
  {'label': 'curiosity', 'score': 0.0008562371367588639},
  {'label': 'nervousness', 'score': 0.0006771065527573228},
  {'label': 'pride', 'score': 0.0005158293060958385}],
 [{'label': 'neutral', 'score': 0.9423111081123352},
  {'label': 'approval', 'score': 0.034236472100019455},
  {'label': 'realization', 'score': 0.02416525036096573},
  {'label': 'annoyance', 'score': 0.006766468286514282},
  {'label': 'admiration', 'score': 0.005985400639474392},
  {'label': 'sadness', 'score': 0.0054761734791100025},
  {'label': 'disappointment', 'score': 0.004732138477265835},
  {'label': 'optimism', 'score': 0.0037233922630548477},
  {'label': 'disapproval', 'score': 0.0034888610243797302},
  {'label': 'disgust', 'score': 0.0022891175467520952},
  {'label': 'fear', 'score': 0.0019254916114732623},
  {'label': 'anger', 'score': 0.0016113482415676117},
  {'label': 'confusion', 'score': 0.0015487544005736709},
  {'label': 'desire', 'score': 0.001407438307069242},
  {'label': 'caring', 'score': 0.0013327645137906075},
  {'label': 'amusement', 'score': 0.001233514747582376},
  {'label': 'joy', 'score': 0.0011541952844709158},
  {'label': 'gratitude', 'score': 0.0011314436560496688},
  {'label': 'excitement', 'score': 0.0009034093236550689},
  {'label': 'curiosity', 'score': 0.0008207091013900936},
  {'label': 'love', 'score': 0.0008027013391256332},
  {'label': 'surprise', 'score': 0.0007140392553992569},
  {'label': 'grief', 'score': 0.0007081392104737461},
  {'label': 'embarrassment', 'score': 0.0006961344042792916},
  {'label': 'relief', 'score': 0.0006308654556050897},
  {'label': 'pride', 'score': 0.0006148181855678558},
  {'label': 'remorse', 'score': 0.0005936566740274429},
  {'label': 'nervousness', 'score': 0.00043113165884278715}],
 [{'label': 'sadness', 'score': 0.7170383930206299},
  {'label': 'neutral', 'score': 0.2270517349243164},
  {'label': 'disappointment', 'score': 0.03747536614537239},
  {'label': 'caring', 'score': 0.03551098331809044},
  {'label': 'grief', 'score': 0.022810181602835655},
  {'label': 'remorse', 'score': 0.022793447598814964},
  {'label': 'approval', 'score': 0.021102720871567726},
  {'label': 'realization', 'score': 0.02085627242922783},
  {'label': 'nervousness', 'score': 0.009491332806646824},
  {'label': 'desire', 'score': 0.007585062179714441},
  {'label': 'annoyance', 'score': 0.007165498565882444},
  {'label': 'fear', 'score': 0.005749270785599947},
  {'label': 'love', 'score': 0.0049141934141516685},
  {'label': 'disapproval', 'score': 0.0044105383567512035},
  {'label': 'joy', 'score': 0.0043192156590521336},
  {'label': 'admiration', 'score': 0.0042663984932005405},
  {'label': 'optimism', 'score': 0.003972639795392752},
  {'label': 'relief', 'score': 0.0038718804717063904},
  {'label': 'disgust', 'score': 0.0027551911771297455},
  {'label': 'anger', 'score': 0.002716466784477234},
  {'label': 'embarrassment', 'score': 0.002129608066752553},
  {'label': 'confusion', 'score': 0.0019996806513518095},
  {'label': 'amusement', 'score': 0.0018111105309799314},
  {'label': 'curiosity', 'score': 0.0015943972393870354},
  {'label': 'gratitude', 'score': 0.0015786235453560948},
  {'label': 'excitement', 'score': 0.0012141522020101547},
  {'label': 'surprise', 'score': 0.0009485887130722404},
  {'label': 'pride', 'score': 0.0008664465276524425}],
 [{'label': 'joy', 'score': 0.7413573265075684},
  {'label': 'admiration', 'score': 0.1740368753671646},
  {'label': 'approval', 'score': 0.09558122605085373},
  {'label': 'neutral', 'score': 0.07788774371147156},
  {'label': 'excitement', 'score': 0.049850963056087494},
  {'label': 'amusement', 'score': 0.027041317895054817},
  {'label': 'pride', 'score': 0.018388209864497185},
  {'label': 'relief', 'score': 0.017696566879749298},
  {'label': 'love', 'score': 0.012335100211203098},
  {'label': 'annoyance', 'score': 0.011396301910281181},
  {'label': 'realization', 'score': 0.009998842142522335},
  {'label': 'optimism', 'score': 0.0087283281609416},
  {'label': 'caring', 'score': 0.006444080267101526},
  {'label': 'disapproval', 'score': 0.0039900075644254684},
  {'label': 'disappointment', 'score': 0.003481769235804677},
  {'label': 'gratitude', 'score': 0.003122171387076378},
  {'label': 'desire', 'score': 0.0027519098948687315},
  {'label': 'anger', 'score': 0.0024055507965385914},
  {'label': 'sadness', 'score': 0.002400921192020178},
  {'label': 'surprise', 'score': 0.0015793481143191457},
  {'label': 'nervousness', 'score': 0.001080264337360859},
  {'label': 'grief', 'score': 0.0009937381837517023},
  {'label': 'embarrassment', 'score': 0.0009483290486969054},
  {'label': 'disgust', 'score': 0.000913748808670789},
  {'label': 'curiosity', 'score': 0.0008255866705439985},
  {'label': 'confusion', 'score': 0.0008174808463081717},
  {'label': 'fear', 'score': 0.0006173051078803837},
  {'label': 'remorse', 'score': 0.0003333486965857446}],
 [{'label': 'admiration', 'score': 0.692378580570221},
  {'label': 'neutral', 'score': 0.1759381741285324},
  {'label': 'approval', 'score': 0.16847126185894012},
  {'label': 'excitement', 'score': 0.03926482051610947},
  {'label': 'surprise', 'score': 0.008807436563074589},
  {'label': 'realization', 'score': 0.00839807279407978},
  {'label': 'optimism', 'score': 0.007704547606408596},
  {'label': 'pride', 'score': 0.004883472807705402},
  {'label': 'joy', 'score': 0.004676769953221083},
  {'label': 'annoyance', 'score': 0.003625574754551053},
  {'label': 'curiosity', 'score': 0.003303535282611847},
  {'label': 'love', 'score': 0.0031879900489002466},
  {'label': 'disapproval', 'score': 0.0023688292130827904},
  {'label': 'disappointment', 'score': 0.0020747315138578415},
  {'label': 'confusion', 'score': 0.001657560933381319},
  {'label': 'gratitude', 'score': 0.0015371968038380146},
  {'label': 'desire', 'score': 0.0013163560070097446},
  {'label': 'amusement', 'score': 0.0012664987007156014},
  {'label': 'anger', 'score': 0.0009398508118465543},
  {'label': 'caring', 'score': 0.000862625427544117},
  {'label': 'disgust', 'score': 0.0006821205606684089},
  {'label': 'relief', 'score': 0.0006726335268467665},
  {'label': 'fear', 'score': 0.000561497756280005},
  {'label': 'sadness', 'score': 0.0004433483991306275},
  {'label': 'embarrassment', 'score': 0.00031752846552990377},
  {'label': 'grief', 'score': 0.0002563344605732709},
  {'label': 'nervousness', 'score': 0.00017763077630661428},
  {'label': 'remorse', 'score': 0.00016375313862226903}],
 [{'label': 'neutral', 'score': 0.9549601674079895},
  {'label': 'approval', 'score': 0.022920334711670876},
  {'label': 'disapproval', 'score': 0.009044048376381397},
  {'label': 'realization', 'score': 0.008665140718221664},
  {'label': 'annoyance', 'score': 0.006453509442508221},
  {'label': 'disappointment', 'score': 0.005593900103121996},
  {'label': 'admiration', 'score': 0.00497800949960947},
  {'label': 'sadness', 'score': 0.002301156288012862},
  {'label': 'optimism', 'score': 0.002142632147297263},
  {'label': 'confusion', 'score': 0.002089390531182289},
  {'label': 'excitement', 'score': 0.001905130920931697},
  {'label': 'joy', 'score': 0.0016943661030381918},
  {'label': 'anger', 'score': 0.001534470939077437},
  {'label': 'disgust', 'score': 0.0014689203817397356},
  {'label': 'gratitude', 'score': 0.0013705722521990538},
  {'label': 'amusement', 'score': 0.001089825644157827},
  {'label': 'fear', 'score': 0.001050856662914157},
  {'label': 'desire', 'score': 0.0010161612881347537},
  {'label': 'curiosity', 'score': 0.000984524260275066},
  {'label': 'surprise', 'score': 0.0009003463201224804},
  {'label': 'love', 'score': 0.0008973359945230186},
  {'label': 'caring', 'score': 0.0008596854167990386},
  {'label': 'embarrassment', 'score': 0.0006433890666812658},
  {'label': 'relief', 'score': 0.0005002192920073867},
  {'label': 'pride', 'score': 0.0004335329285822809},
  {'label': 'remorse', 'score': 0.0004028234106954187},
  {'label': 'grief', 'score': 0.00039013498462736607},
  {'label': 'nervousness', 'score': 0.00035462036612443626}]]

In [7]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [9]:
sorted(predictions[0], key = lambda x : x["label"])

[{'label': 'admiration', 'score': 0.29842227697372437},
 {'label': 'amusement', 'score': 0.0021955484990030527},
 {'label': 'anger', 'score': 0.001288198516704142},
 {'label': 'annoyance', 'score': 0.002989330794662237},
 {'label': 'approval', 'score': 0.06156652793288231},
 {'label': 'caring', 'score': 0.001193404896184802},
 {'label': 'confusion', 'score': 0.0024072828236967325},
 {'label': 'curiosity', 'score': 0.020611189305782318},
 {'label': 'desire', 'score': 0.012063340283930302},
 {'label': 'disappointment', 'score': 0.0019814688712358475},
 {'label': 'disapproval', 'score': 0.0021141960751265287},
 {'label': 'disgust', 'score': 0.0014362820656970143},
 {'label': 'embarrassment', 'score': 0.00044948080903850496},
 {'label': 'excitement', 'score': 0.4950507879257202},
 {'label': 'fear', 'score': 0.001415332080796361},
 {'label': 'gratitude', 'score': 0.0008985294844023883},
 {'label': 'grief', 'score': 0.0004383960331324488},
 {'label': 'joy', 'score': 0.013649096712470055},
 {'label': 'love', 'score': 0.012229564599692822},
 {'label': 'nervousness', 'score': 0.0006956649012863636},
 {'label': 'neutral', 'score': 0.11334887892007828},
 {'label': 'optimism', 'score': 0.005851097404956818},
 {'label': 'pride', 'score': 0.0025997976772487164},
 {'label': 'realization', 'score': 0.004697063472121954},
 {'label': 'relief', 'score': 0.0008879499509930611},
 {'label': 'remorse', 'score': 0.0002430182066746056},
 {'label': 'sadness', 'score': 0.001169283059425652},
 {'label': 'surprise', 'score': 0.025452643632888794}]

In [11]:
import numpy as np

emotion_labels = [
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "neutral",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise"
]

In [12]:
isbn = []
emotion_scores = {label : [] for label in emotion_labels}

def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label : [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction , key = lambda x : x["label"])
        for index , label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label :np.max(scores) for label , scores in per_emotion_scores.items()}

In [13]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [14]:
emotion_scores

{'admiration': [np.float64(0.692378580570221),
  np.float64(0.8429386019706726),
  np.float64(0.8438481688499451),
  np.float64(0.21287216246128082),
  np.float64(0.624519407749176),
  np.float64(0.01607689820230007),
  np.float64(0.8295944929122925),
  np.float64(0.934485912322998),
  np.float64(0.05251738801598549),
  np.float64(0.00497800949960947)],
 'amusement': [np.float64(0.027041317895054817),
  np.float64(0.0023722785990685225),
  np.float64(0.0017943830462172627),
  np.float64(0.0015534177655354142),
  np.float64(0.003031004685908556),
  np.float64(0.0019459299510344863),
  np.float64(0.0023236998822540045),
  np.float64(0.012667234055697918),
  np.float64(0.00250267400406301),
  np.float64(0.0027869325131177902)],
 'anger': [np.float64(0.002716466784477234),
  np.float64(0.0042837029322981834),
  np.float64(0.04729495942592621),
  np.float64(0.013755356892943382),
  np.float64(0.005192018114030361),
  np.float64(0.00282081076875329),
  np.float64(0.00975851435214281),
  np.float64(0.0029164887964725494),
  np.float64(0.004458618815988302),
  np.float64(0.0032089974265545607)],
 'annoyance': [np.float64(0.011396301910281181),
  np.float64(0.015322037041187286),
  np.float64(0.03773144260048866),
  np.float64(0.017027772963047028),
  np.float64(0.011019326746463776),
  np.float64(0.01937260664999485),
  np.float64(0.13249485194683075),
  np.float64(0.006453509442508221),
  np.float64(0.06916262209415436),
  np.float64(0.006453509442508221)],
 'approval': [np.float64(0.16847126185894012),
  np.float64(0.06941189616918564),
  np.float64(0.0675317794084549),
  np.float64(0.45013365149497986),
  np.float64(0.3380613327026367),
  np.float64(0.09100811183452606),
  np.float64(0.12049935758113861),
  np.float64(0.05853111296892166),
  np.float64(0.07161394506692886),
  np.float64(0.023192662745714188)],
 'caring': [np.float64(0.03551098331809044),
  np.float64(0.0034281259868294),
  np.float64(0.005412057042121887),
  np.float64(0.04705008491873741),
  np.float64(0.17668423056602478),
  np.float64(0.0010082455119118094),
  np.float64(0.010578970424830914),
  np.float64(0.0033523140009492636),
  np.float64(0.004922690335661173),
  np.float64(0.001087530399672687)],
 'confusion': [np.float64(0.0024072828236967325),
  np.float64(0.3190416097640991),
  np.float64(0.004081387538462877),
  np.float64(0.005814047530293465),
  np.float64(0.061917684972286224),
  np.float64(0.009557385928928852),
  np.float64(0.03175400197505951),
  np.float64(0.0027998003643006086),
  np.float64(0.16604264080524445),
  np.float64(0.002691089641302824)],
 'curiosity': [np.float64(0.020611189305782318),
  np.float64(0.19671224057674408),
  np.float64(0.0016204176936298609),
  np.float64(0.0020340716000646353),
  np.float64(0.27654409408569336),
  np.float64(0.004658133257180452),
  np.float64(0.004926594905555248),
  np.float64(0.0025317927356809378),
  np.float64(0.557991087436676),
  np.float64(0.0016405492788180709)],
 'desire': [np.float64(0.012063340283930302),
  np.float64(0.01209400873631239),
  np.float64(0.003371239174157381),
  np.float64(0.0030081146396696568),
  np.float64(0.027690164744853973),
  np.float64(0.0013568521244451404),
  np.float64(0.020201100036501884),
  np.float64(0.0051372055895626545),
  np.float64(0.0026953225024044514),
  np.float64(0.0011503531131893396)],
 'disappointment': [np.float64(0.03747536614537239),
  np.float64(0.008344070985913277),
  np.float64(0.024637985974550247),
  np.float64(0.025365745648741722),
  np.float64(0.015684431418776512),
  np.float64(0.04987042769789696),
  np.float64(0.2645462155342102),
  np.float64(0.009820082224905491),
  np.float64(0.04592759162187576),
  np.float64(0.005593900103121996)],
 'disapproval': [np.float64(0.009044048376381397),
  np.float64(0.01069733127951622),
  np.float64(0.02792191505432129),
  np.float64(0.038544848561286926),
  np.float64(0.014112246222794056),
  np.float64(0.01087086834013462),
  np.float64(0.2586703300476074),
  np.float64(0.009044048376381397),
  np.float64(0.10475369542837143),
  np.float64(0.009044048376381397)],
 'disgust': [np.float64(0.0027551911771297455),
  np.float64(0.0027582652401179075),
  np.float64(0.010160157456994057),
  np.float64(0.007591733708977699),
  np.float64(0.002779544796794653),
  np.float64(0.005427445750683546),
  np.float64(0.005339157301932573),
  np.float64(0.0021674330346286297),
  np.float64(0.010195428505539894),
  np.float64(0.0021536066196858883)],
 'embarrassment': [np.float64(0.002129608066752553),
  np.float64(0.0021378479432314634),
  np.float64(0.0023371241986751556),
  np.float64(0.0014101744163781404),
  np.float64(0.0012546847574412823),
  np.float64(0.003355348715558648),
  np.float64(0.004394307732582092),
  np.float64(0.00475696288049221),
  np.float64(0.005524114705622196),
  np.float64(0.0008792546577751637)],
 'excitement': [np.float64(0.4950507879257202),
  np.float64(0.006602156907320023),
  np.float64(0.0033774503972381353),
  np.float64(0.004655500873923302),
  np.float64(0.003976116422563791),
  np.float64(0.0053289118222892284),
  np.float64(0.0040534138679504395),
  np.float64(0.16559681296348572),
  np.float64(0.004191974177956581),
  np.float64(0.0036981143057346344)],
 'fear': [np.float64(0.005749270785599947),
  np.float64(0.007729303557425737),
  np.float64(0.42973095178604126),
  np.float64(0.11171646416187286),
  np.float64(0.0022661960683763027),
  np.float64(0.003891882486641407),
  np.float64(0.19972941279411316),
  np.float64(0.009991127997636795),
  np.float64(0.01696714386343956),
  np.float64(0.002088400302454829)],
 'gratitude': [np.float64(0.003122171387076378),
  np.float64(0.004498503636568785),
  np.float64(0.002397360047325492),
  np.float64(0.001882375916466117),
  np.float64(0.027513450011610985),
  np.float64(0.0013705722521990538),
  np.float64(0.01743151992559433),
  np.float64(0.020486969500780106),
  np.float64(0.0017378951888531446),
  np.float64(0.0013705722521990538)],
 'grief': [np.float64(0.022810181602835655),
  np.float64(0.002033769618719816),
  np.float64(0.0013573199976235628),
  np.float64(0.0030921970028430223),
  np.float64(0.001541474717669189),
  np.float64(0.0021873905789107084),
  np.float64(0.0017342319479212165),
  np.float64(0.010866383090615273),
  np.float64(0.007081227842718363),
  np.float64(0.0006272920873016119)],
 'joy': [np.float64(0.7413573265075684),
  np.float64(0.003938135225325823),
  np.float64(0.0025672719348222017),
  np.float64(0.005266180727630854),
  np.float64(0.0034977977629750967),
  np.float64(0.0020171490032225847),
  np.float64(0.003270618850365281),
  np.float64(0.3175084590911865),
  np.float64(0.0026295434217900038),
  np.float64(0.003894498571753502)],
 'love': [np.float64(0.012335100211203098),
  np.float64(0.002380378544330597),
  np.float64(0.04072612524032593),
  np.float64(0.3779677748680115),
  np.float64(0.004655494354665279),
  np.float64(0.001859212527051568),
  np.float64(0.0020092728082090616),
  np.float64(0.0049473075196146965),
  np.float64(0.003767407266423106),
  np.float64(0.0013717631809413433)],
 'nervousness': [np.float64(0.009491332806646824),
  np.float64(0.002757072914391756),
  np.float64(0.012110010720789433),
  np.float64(0.014452707953751087),
  np.float64(0.0008792031439952552),
  np.float64(0.0012335276696830988),
  np.float64(0.01333449874073267),
  np.float64(0.009201585315167904),
  np.float64(0.003734011435881257),
  np.float64(0.0005637296126224101)],
 'neutral': [np.float64(0.9549601674079895),
  np.float64(0.96993488073349),
  np.float64(0.9549601674079895),
  np.float64(0.9549601674079895),
  np.float64(0.9677259922027588),
  np.float64(0.9549601674079895),
  np.float64(0.9569121599197388),
  np.float64(0.9549601674079895),
  np.float64(0.9612938761711121),
  np.float64(0.9622653722763062)],
 'optimism': [np.float64(0.0087283281609416),
  np.float64(0.009755943901836872),
  np.float64(0.010674958117306232),
  np.float64(0.010419690050184727),
  np.float64(0.44938376545906067),
  np.float64(0.004559598863124847),
  np.float64(0.11516307294368744),
  np.float64(0.0053738937713205814),
  np.float64(0.015621365047991276),
  np.float64(0.0025780689902603626)],
 'pride': [np.float64(0.018388209864497185),
  np.float64(0.0037469405215233564),
  np.float64(0.004599837586283684),
  np.float64(0.00417657196521759),
  np.float64(0.004905350040644407),
  np.float64(0.0016677012899890542),
  np.float64(0.006487651728093624),
  np.float64(0.00701083242893219),
  np.float64(0.0008276239968836308),
  np.float64(0.0005016230861656368)],
 'realization': [np.float64(0.030264271423220634),
  np.float64(0.05541606992483139),
  np.float64(0.02982545830309391),
  np.float64(0.09270350635051727),
  np.float64(0.014125892892479897),
  np.float64(0.18218806385993958),
  np.float64(0.03183858096599579),
  np.float64(0.050153471529483795),
  np.float64(0.030035944655537605),
  np.float64(0.01759803295135498)],
 'relief': [np.float64(0.017696566879749298),
  np.float64(0.0013366483617573977),
  np.float64(0.0017796955071389675),
  np.float64(0.0026823338121175766),
  np.float64(0.004011687822639942),
  np.float64(0.002200918272137642),
  np.float64(0.0015182687202468514),
  np.float64(0.01692086085677147),
  np.float64(0.001741512562148273),
  np.float64(0.0005848731379956007)],
 'remorse': [np.float64(0.022793447598814964),
  np.float64(0.0013001461047679186),
  np.float64(0.0007893607253208756),
  np.float64(0.0022817151620984077),
  np.float64(0.0017100583063438535),
  np.float64(0.0015856977552175522),
  np.float64(0.0058026690967381),
  np.float64(0.0021454666275531054),
  np.float64(0.0019228562014177442),
  np.float64(0.00043219036888331175)],
 'sadness': [np.float64(0.7170383930206299),
  np.float64(0.017485816031694412),
  np.float64(0.009665755555033684),
  np.float64(0.025013349950313568),
  np.float64(0.011587215587496758),
  np.float64(0.0325160026550293),
  np.float64(0.04735114797949791),
  np.float64(0.05414228513836861),
  np.float64(0.15950705111026764),
  np.float64(0.002985561266541481)],
 'surprise': [np.float64(0.025452643632888794),
  np.float64(0.008590376935899258),
  np.float64(0.002096201991662383),
  np.float64(0.0018759487429633737),
  np.float64(0.0035546058788895607),
  np.float64(0.012824623845517635),
  np.float64(0.003425493137910962),
  np.float64(0.06163269281387329),
  np.float64(0.01999272033572197),
  np.float64(0.001633923500776291)]}

In [16]:
from tqdm import tqdm

emotion_labels = [
    "admiration",
    "amusement",
    "anger",
    "annoyance",
    "approval",
    "caring",
    "confusion",
    "curiosity",
    "desire",
    "disappointment",
    "disapproval",
    "disgust",
    "embarrassment",
    "excitement",
    "fear",
    "gratitude",
    "grief",
    "joy",
    "love",
    "nervousness",
    "neutral",
    "optimism",
    "pride",
    "realization",
    "relief",
    "remorse",
    "sadness",
    "surprise"
]

isbn = []
emotion_scores = {label : [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5197/5197 [13:31<00:00,  6.40it/s]

In [17]:
emotions_df= pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [18]:
emotions_df.head()

,admiration,amusement,anger,annoyance,approval,caring,confusion,curiosity,desire,disappointment,...,nervousness,neutral,optimism,pride,realization,relief,remorse,sadness,surprise,isbn13
0,0.692379,0.027041,0.002716,0.011396,0.168471,0.035511,0.002407,0.020611,0.012063,0.037475,...,0.009491,0.954960,0.008728,0.018388,0.030264,0.017697,0.022793,0.717038,0.025453,9780002005883
1,0.842939,0.002372,0.004284,0.015322,0.069412,0.003428,0.319042,0.196712,0.012094,0.008344,...,0.002757,0.969935,0.009756,0.003747,0.055416,0.001337,0.001300,0.017486,0.008590,9780002261982
2,0.843848,0.001794,0.047295,0.037731,0.067532,0.005412,0.004081,0.001620,0.003371,0.024638,...,0.012110,0.954960,0.010675,0.004600,0.029825,0.001780,0.000789,0.009666,0.002096,9780006178736
3,0.212872,0.001553,0.013755,0.017028,0.450134,0.047050,0.005814,0.002034,0.003008,0.025366,...,0.014453,0.954960,0.010420,0.004177,0.092704,0.002682,0.002282,0.025013,0.001876,9780006280897
4,0.624519,0.003031,0.005192,0.011019,0.338061,0.176684,0.061918,0.276544,0.027690,0.015684,...,0.000879,0.967726,0.449384,0.004905,0.014126,0.004012,0.001710,0.011587,0.003555,9780006280934

In [19]:
books = pd.merge(books , emotions_df , on = "isbn13")

In [20]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,love,nervousness,neutral,optimism,pride,realization,relief,remorse,sadness,surprise
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,0.012335,0.009491,0.954960,0.008728,0.018388,0.030264,0.017697,0.022793,0.717038,0.025453
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,0.002380,0.002757,0.969935,0.009756,0.003747,0.055416,0.001337,0.001300,0.017486,0.008590
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,...,0.040726,0.012110,0.954960,0.010675,0.004600,0.029825,0.001780,0.000789,0.009666,0.002096
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,...,0.377968,0.014453,0.954960,0.010420,0.004177,0.092704,0.002682,0.002282,0.025013,0.001876
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,...,0.004655,0.000879,0.967726,0.449384,0.004905,0.014126,0.004012,0.001710,0.011587,0.003555
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,0.077260,0.008361,0.959202,0.005819,0.002451,0.052503,0.002602,0.006266,0.628992,0.045051
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,0.005114,0.000731,0.954960,0.017455,0.005442,0.207877,0.003204,0.001000,0.002334,0.004602
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,0.004229,0.001601,0.511191,0.030445,0.050447,0.061655,0.050487,0.000934,0.004365,0.002558
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,0.002207,0.005281,0.954960,0.049323,0.015377,0.095144,0.010845,0.008603,0.043103,0.009290
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,0.003341,0.000749,0.954960,0.896929,0.005295,0.093907,0.002142,0.002350,0.002398,0.001928

In [21]:
books.to_csv("books_with_emotions.csv" , index = False)