In [1]:
from pickletools import long1

import pandas as pd

In [12]:
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_huggingface import HuggingFaceEmbeddings

In [3]:
from dotenv import load_dotenv

load_dotenv()

True

In [4]:
books = pd.read_csv("books_cleaned.csv")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,Gilead,9780002005883 A NOVEL THAT READERS and critics...
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,Rage of angels,"9780006178736 A memorable, mesmerizing heroine..."
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,The Four Loves,9780006280897 Lewis' work on the nature of lov...
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,The Problem of Pain,"9780006280934 ""In The Problem of Pain, C.S. Le..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,Mistaken Identity,9788172235222 On A Train Journey Home To North...
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,Journey to the East,9788173031014 This book tells the tale of a ma...
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,The Berlin Phenomenology,9789027712059 Since the three volume edition o...

In [5]:
books["tagged_description"]

0       9780002005883 A NOVEL THAT READERS and critics...
1       9780002261982 A new 'Christie for Christmas' -...
2       9780006178736 A memorable, mesmerizing heroine...
3       9780006280897 Lewis' work on the nature of lov...
4       9780006280934 "In The Problem of Pain, C.S. Le...
                              ...
5192    9788172235222 On A Train Journey Home To North...
5193    9788173031014 This book tells the tale of a ma...
5194    9788179921623 Wisdom to Create a Life of Passi...
5195    9788185300535 This collection of the timeless ...
5196    9789027712059 Since the three volume edition o...
Name: tagged_description, Length: 5197, dtype: object

In [6]:
books["tagged_description"].to_csv("tagged_description.txt" ,  index = False , header = False,encoding="utf-8")

In [7]:
raw_documents = TextLoader("tagged_description.txt",encoding="utf-8").load()
text_splitter = CharacterTextSplitter(chunk_size=1 , chunk_overlap=0 , separator= "\n")
documents = text_splitter.split_documents(raw_documents)

Created a chunk of size 1170, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 375, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 483, which is longer than the specified 1
Created a chunk of size 484, which is longer than the specified 1
Created a chunk of size 962, which is longer than the specified 1
Created a chunk of size 188, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 296, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 881, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 270, which is longer than the specified 1
Created a chunk of size 213, which is longer than the specified 1
Created a chunk of size 216, which is longer than the specified 1
Created a chunk of size 515, which is longer than the specified 1
Created a chunk of size 754, which is longer than the specified 1
Created a chunk of size 390, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 253, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 730, which is longer than the specified 1
Created a chunk of size 723, which is longer than the specified 1
Created a chunk of size 258, which is longer than the specified 1
Created a chunk of size 475, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 1267, which is longer than the specified 1
Created a chunk of size 683, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 555, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 282, which is longer than the specified 1
Created a chunk of size 789, which is longer than the specified 1
Created a chunk of size 566, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 299, which is longer than the specified 1
Created a chunk of size 535, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 565, which is longer than the specified 1
Created a chunk of size 385, which is longer than the specified 1
Created a chunk of size 412, which is longer than the specified 1
Created a chunk of size 463, which is longer than the specified 1
Created a chunk of size 597, which is longer than the specified 1
Created a chunk of size 478, which is longer than the specified 1
Created a chunk of size 461, which is longer than the specified 1
Created a chunk of size 259, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 616, which is longer than the specified 1
Created a chunk of size 421, which is longer than the specified 1
Created a chunk of size 889, which is longer than the specified 1
Created a chunk of size 695, which is longer than the specified 1
Created a chunk of size 304, which is longer than the specified 1
Created a chunk of size 219, which is longer than the specified 1
Created a chunk of size 277, which is longer than the specified 1
Created a chunk of size 2010, which is longer than the specified 1
Created a chunk of size 175, which is longer than the specified 1
Created a chunk of size 481, which is longer than the specified 1
Created a chunk of size 302, which is longer than the specified 1
Created a chunk of size 522, which is longer than the specified 1
Created a chunk of size 649, which is longer than the specified 1
Created a chunk of size 778, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 688, which is longer than the specified 1
Created a chunk of size 550, which is longer than the specified 1
Created a chunk of size 1225, which is longer than the specified 1
Created a chunk of size 408, which is longer than the specified 1
Created a chunk of size 1186, which is longer than the specified 1
Created a chunk of size 1216, which is longer than the specified 1
Created a chunk of size 1193, which is longer than the specified 1
Created a chunk of size 1059, which is longer than the specified 1
Created a chunk of size 246, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 878, which is longer than the specified 1
Created a chunk of size 286, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 389, which is longer than the specified 1
Created a chunk of size 419, which is longer than the specified 1
Created a chunk of size 210, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 163, which is longer than the specified 1
Created a chunk of size 528, which is longer than the specified 1
Created a chunk of size 523, which is longer than the specified 1
Created a chunk of size 214, which is longer than the specified 1
Created a chunk of size 340, which is longer than the specified 1
Created a chunk of size 901, which is longer than the specified 1
Created a chunk of size 1272, which is longer than the specified 1
Created a chunk of size 560, which is longer than the specified 1
Created a chunk of size 1637, which is longer than the specified 1
Created a chunk of size 438, which is longer than the specified 1
Created a chunk of size 251, which is longer than the specified 1
Created a chunk of size 779, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 516, which is longer than the specified 1
Created a chunk of size 960, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1132, which is longer than the specified 1
Created a chunk of size 170, which is longer than the specified 1
Created a chunk of size 1325, which is longer than the specified 1
Created a chunk of size 853, which is longer than the specified 1
Created a chunk of size 272, which is longer than the specified 1
Created a chunk of size 801, which is longer than the specified 1
Created a chunk of size 1121, which is longer than the specified 1
Created a chunk of size 838, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 734, which is longer than the specified 1
Created a chunk of size 1195, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 775, which is longer than the specified 1
Created a chunk of size 280, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 358, which is longer than the specified 1
Created a chunk of size 768, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 718, which is longer than the specified 1
Created a chunk of size 2012, which is longer than the specified 1
Created a chunk of size 308, which is longer than the specified 1
Created a chunk of size 1288, which is longer than the specified 1
Created a chunk of size 1231, which is longer than the specified 1
Created a chunk of size 729, which is longer than the specified 1
Created a chunk of size 750, which is longer than the specified 1
Created a chunk of size 447, which is longer than the specified 1
Created a chunk of size 1242, which is longer than the specified 1
Created a chunk of size 311, which is longer than the specified 1
Created a chunk of size 914, which is longer than the specified 1
Created a chunk of size 306, which is longer than the specified 1
Created a chunk of size 846, which is longer than the specified 1
Created a chunk of size 1128, which is longer than the specified 1
Created a chunk of size 1075, which is longer than the specified 1
Created a chunk of size 1320, which is longer than the specified 1
Created a chunk of size 363, which is longer than the specified 1
Created a chunk of size 2834, which is longer than the specified 1
Created a chunk of size 237, which is longer than the specified 1
Created a chunk of size 242, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 208, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 1006, which is longer than the specified 1
Created a chunk of size 715, which is longer than the specified 1
Created a chunk of size 712, which is longer than the specified 1
Created a chunk of size 2510, which is longer than the specified 1
Created a chunk of size 956, which is longer than the specified 1
Created a chunk of size 309, which is longer than the specified 1
Created a chunk of size 351, which is longer than the specified 1
Created a chunk of size 641, which is longer than the specified 1
Created a chunk of size 405, which is longer than the specified 1
Created a chunk of size 525, which is longer than the specified 1
Created a chunk of size 795, which is longer than the specified 1
Created a chunk of size 167, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 1424, which is longer than the specified 1
Created a chunk of size 1085, which is longer than the specified 1
Created a chunk of size 1146, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 790, which is longer than the specified 1
Created a chunk of size 297, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 256, which is longer than the specified 1
Created a chunk of size 876, which is longer than the specified 1
Created a chunk of size 808, which is longer than the specified 1
Created a chunk of size 1814, which is longer than the specified 1
Created a chunk of size 1830, which is longer than the specified 1
Created a chunk of size 1064, which is longer than the specified 1
Created a chunk of size 955, which is longer than the specified 1
Created a chunk of size 1182, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 283, which is longer than the specified 1
Created a chunk of size 288, which is longer than the specified 1
Created a chunk of size 1286, which is longer than the specified 1
Created a chunk of size 1644, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 1932, which is longer than the specified 1
Created a chunk of size 874, which is longer than the specified 1
Created a chunk of size 2008, which is longer than the specified 1
Created a chunk of size 2285, which is longer than the specified 1
Created a chunk of size 173, which is longer than the specified 1
Created a chunk of size 1003, which is longer than the specified 1
Created a chunk of size 579, which is longer than the specified 1
Created a chunk of size 290, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 1144, which is longer than the specified 1
Created a chunk of size 559, which is longer than the specified 1
Created a chunk of size 1143, which is longer than the specified 1
Created a chunk of size 245, which is longer than the specified 1
Created a chunk of size 1088, which is longer than the specified 1
Created a chunk of size 1483, which is longer than the specified 1
Created a chunk of size 223, which is longer than the specified 1
Created a chunk of size 1137, which is longer than the specified 1
Created a chunk of size 724, which is longer than the specified 1
Created a chunk of size 668, which is longer than the specified 1
Created a chunk of size 767, which is longer than the specified 1
Created a chunk of size 608, which is longer than the specified 1
Created a chunk of size 572, which is longer than the specified 1
Created a chunk of size 967, which is longer than the specified 1
Created a chunk of size 859, which is longer than the specified 1
Created a chunk of size 1034, which is longer than the specified 1
Created a chunk of size 191, which is longer than the specified 1
Created a chunk of size 367, which is longer than the specified 1
Created a chunk of size 497, which is longer than the specified 1
Created a chunk of size 652, which is longer than the specified 1
Created a chunk of size 350, which is longer than the specified 1
Created a chunk of size 735, which is longer than the specified 1
Created a chunk of size 527, which is longer than the specified 1
Created a chunk of size 1017, which is longer than the specified 1
Created a chunk of size 972, which is longer than the specified 1
Created a chunk of size 206, which is longer than the specified 1
Created a chunk of size 690, which is longer than the specified 1
Created a chunk of size 546, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 209, which is longer than the specified 1
Created a chunk of size 378, which is longer than the specified 1
Created a chunk of size 933, which is longer than the specified 1
Created a chunk of size 564, which is longer than the specified 1
Created a chunk of size 856, which is longer than the specified 1
Created a chunk of size 717, which is longer than the specified 1
Created a chunk of size 749, which is longer than the specified 1
Created a chunk of size 714, which is longer than the specified 1
Created a chunk of size 326, which is longer than the specified 1
Created a chunk of size 243, which is longer than the specified 1
Created a chunk of size 1090, which is longer than the specified 1
Created a chunk of size 725, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 229, which is longer than the specified 1
Created a chunk of size 706, which is longer than the specified 1
Created a chunk of size 1914, which is longer than the specified 1
Created a chunk of size 397, which is longer than the specified 1
Created a chunk of size 487, which is longer than the specified 1
Created a chunk of size 622, which is longer than the specified 1
Created a chunk of size 561, which is longer than the specified 1
Created a chunk of size 558, which is longer than the specified 1
Created a chunk of size 388, which is longer than the specified 1
Created a chunk of size 231, which is longer than the specified 1
Created a chunk of size 427, which is longer than the specified 1
Created a chunk of size 418, which is longer than the specified 1
Created a chunk of size 284, which is longer than the specified 1
Created a chunk of size 168, which is longer than the specified 1
Created a chunk of size 626, which is longer than the specified 1
Created a chunk of size 2616, which is longer than the specified 1
Created a chunk of size 1580, which is longer than the specified 1
Created a chunk of size 391, which is longer than the specified 1
Created a chunk of size 996, which is longer than the specified 1
Created a chunk of size 849, which is longer than the specified 1
Created a chunk of size 265, which is longer than the specified 1
Created a chunk of size 338, which is longer than the specified 1
Created a chunk of size 1530, which is longer than the specified 1
Created a chunk of size 215, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 2032, which is longer than the specified 1
Created a chunk of size 398, which is longer than the specified 1
Created a chunk of size 1619, which is longer than the specified 1
Created a chunk of size 700, which is longer than the specified 1
Created a chunk of size 824, which is longer than the specified 1
Created a chunk of size 356, which is longer than the specified 1
Created a chunk of size 843, which is longer than the specified 1
Created a chunk of size 1191, which is longer than the specified 1
Created a chunk of size 197, which is longer than the specified 1
Created a chunk of size 510, which is longer than the specified 1
Created a chunk of size 665, which is longer than the specified 1
Created a chunk of size 1284, which is longer than the specified 1
Created a chunk of size 262, which is longer than the specified 1
Created a chunk of size 244, which is longer than the specified 1
Created a chunk of size 217, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1268, which is longer than the specified 1
Created a chunk of size 1277, which is longer than the specified 1
Created a chunk of size 200, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1
Created a chunk of size 380, which is longer than the specified 1
Created a chunk of size 271, which is longer than the specified 1
Created a chunk of size 179, which is longer than the specified 1
Created a chunk of size 227, which is longer than the specified 1
Created a chunk of size 224, which is longer than the specified 1
Created a chunk of size 784, which is longer than the specified 1
Created a chunk of size 971, which is longer than the specified 1
Created a chunk of size 615, which is longer than the specified 1
Created a chunk of size 165, which is longer than the specified 1
Created a chunk of size 759, which is longer than the specified 1
Created a chunk of size 291, which is longer than the specified 1
Created a chunk of size 247, which is longer than the specified 1
Created a chunk of size 965, which is longer than the specified 1
Created a chunk of size 234, which is longer than the specified 1
Created a chunk of size 845, which is longer than the specified 1
Created a chunk of size 788, which is longer than the specified 1
Created a chunk of size 650, which is longer than the specified 1
Created a chunk of size 986, which is longer than the specified 1
Created a chunk of size 799, which is longer than the specified 1
Created a chunk of size 193, which is longer than the specified 1
Created a chunk of size 1163, which is longer than the specified 1
Created a chunk of size 255, which is longer than the specified 1
Created a chunk of size 203, which is longer than the specified 1
Created a chunk of size 1058, which is longer than the specified 1

In [8]:
len(documents)

5197

In [14]:
emb = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en")  #embedding used
db_books = Chroma.from_documents(documents, embedding=emb)

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

C:\Users\LENOVO\PycharmProjects\PythonProject\Book_recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\LENOVO\.cache\huggingface\hub\models--BAAI--bge-small-en. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/684 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [45]:
db_books

In [32]:
query = "what is best book to learn about nature trees and plants "

ans = db_books.similarity_search(query , k = 2)
ans

[Document(id='5650a19d-8883-4bb9-9e70-7f9e9a47271b', metadata={'source': 'tagged_description.txt'}, page_content='"9780789458209 Photographs and text explore the anatomy and life cycle of trees, examining the different kinds of bark, seeds, and leaves, the commercial processing of trees to make lumber, the creatures that live in trees, and other aspects."'),
 Document(id='1f1d3d9f-5495-433b-9a66-4f54935f5812', metadata={'source': 'tagged_description.txt'}, page_content='"9780786808069 Children will discover the exciting world of their own backyard in this introduction to familiar animals from cats and dogs to bugs and frogs. The combination of photographs, illustrations, and fun facts make this an accessible and delightful learning experience."')]

In [27]:
books[books["isbn13"] == int(ans[0].page_content.split()[0].strip('\"'))]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,Tree,9780789458209 Photographs and text explore the...

In [43]:
def retrieve_semantic_books_recommendation(user_query, k):
    recommended_books=db_books.similarity_search(user_query,k)

    books_list = []

    for i in range(len(recommended_books)):
        books_list += [int(recommended_books[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)].head(k)

In [44]:
retrieve_semantic_books_recommendation("i need a book to learn about world psychology", 2)

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
1177,9780312151225,0312151225,The Everyday I Ching,Sarah Dening,"Body, Mind & Spirit",http://books.google.com/books/content?id=i5j0Z...,Details how to use the ancient Chinese book of...,1997.0,4.19,224.0,23.0,The Everyday I Ching,9780312151225 Details how to use the ancient C...
2440,9780452281325,0452281326,The Feeling Good Handbook,David D. Burns,Psychology,http://books.google.com/books/content?id=akVIQ...,"Discusses how to overcome fears, phobias, and ...",1999.0,4.00,729.0,4666.0,The Feeling Good Handbook,"9780452281325 Discusses how to overcome fears,..."